# Generated by Django 5.1.15 on 2026-08-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='debe cambiar contraseña'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='código de estudiante'),
        ),
    ]
