# Generated by Django 5.1.15 on 2026-07-16 06:09

import django.db.models.deletion
import tutor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(default=tutor.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente IA')], max_length=16, verbose_name='rol')),
                ('content', models.TextField(verbose_name='contenido')),
                ('context', models.CharField(blank=True, default='', max_length=255, verbose_name='contexto')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='calificación (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha/hora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensaje de chat',
                'verbose_name_plural': 'mensajes de chat',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='tutor_chatm_user_id_1270c0_idx'), models.Index(fields=['user', 'role'], name='tutor_chatm_user_id_d4ec8e_idx')],
            },
        ),
    ]
