# Generated by Django 5.1.15 on 2026-07-16 06:09

import django.db.models.deletion
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.CharField(default=learning.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('icon', models.CharField(default='Award', max_length=64, verbose_name='icono')),
                ('tier', models.CharField(choices=[('bronze', 'Bronce'), ('silver', 'Plata'), ('gold', 'Oro')], default='bronze', max_length=16, verbose_name='nivel')),
            ],
            options={
                'verbose_name': 'insignia',
                'verbose_name_plural': 'insignias',
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.CharField(default=learning.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('confidence', models.IntegerField(verbose_name='confianza (1-5)')),
                ('reflection', models.TextField(blank=True, default='', verbose_name='reflexión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_assessments', to='curriculum.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'autoevaluación',
                'verbose_name_plural': 'autoevaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.CharField(default=learning.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('answer', models.TextField(verbose_name='respuesta')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='retroalimentación IA')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='puntaje')),
                ('correct', models.BooleanField(blank=True, null=True, verbose_name='¿correcta?')),
                ('time_spent', models.IntegerField(blank=True, null=True, verbose_name='tiempo (s)')),
                ('hints_used', models.IntegerField(default=0, verbose_name='pistas usadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha/hora')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='curriculum.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'intento',
                'verbose_name_plural': 'intentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity'], name='learning_at_user_id_c4cb8d_idx'), models.Index(fields=['user', 'correct'], name='learning_at_user_id_308cd4_idx'), models.Index(fields=['activity'], name='learning_at_activit_515f6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.CharField(default=learning.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='curriculum.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'marcador',
                'verbose_name_plural': 'marcadores',
                'indexes': [models.Index(fields=['user'], name='learning_bo_user_id_36184f_idx')],
                'unique_together': {('user', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.CharField(default=learning.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('chat', 'Chat'), ('activity', 'Actividad'), ('content', 'Contenido')], max_length=16, verbose_name='origen')),
                ('source_id', models.CharField(blank=True, default='', max_length=40, verbose_name='ID origen')),
                ('reason', models.CharField(choices=[('incorrect', 'Incorrecta'), ('biased', 'Sesgada'), ('offtopic', 'Fuera de tema'), ('harmful', 'Dañina'), ('other', 'Otra')], max_length=16, verbose_name='razón')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comentario')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('reviewed', 'Revisado'), ('resolved', 'Resuelto')], default='open', max_length=16, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte de error IA',
                'verbose_name_plural': 'reportes de error IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='learning_er_user_id_a01453_idx'), models.Index(fields=['status'], name='learning_er_status_9ab8e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.CharField(default=learning.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('completed', models.IntegerField(default=0, verbose_name='completadas')),
                ('total', models.IntegerField(default=0, verbose_name='total')),
                ('mastery', models.IntegerField(default=0, verbose_name='dominio (%)')),
                ('last_visited', models.DateTimeField(blank=True, null=True, verbose_name='última visita')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='curriculum.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progreso',
                'verbose_name_plural': 'progresos',
                'unique_together': {('user', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.CharField(default=learning.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='inicio')),
                ('duration', models.IntegerField(default=0, verbose_name='duración (s)')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='último heartbeat')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='curriculum.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesión de estudio',
                'verbose_name_plural': 'sesiones de estudio',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='learning_st_user_id_fdaa53_idx'), models.Index(fields=['is_active'], name='learning_st_is_acti_472f8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.CharField(default=learning.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='learning.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'insignia otorgada',
                'verbose_name_plural': 'insignias otorgadas',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
