# Generated by Django 5.1.15 on 2026-07-24 01:05

import django.db.models.deletion
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_unit_content_unit_diagnostic_questions'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=learning.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('diagnostic_answers', models.JSONField(default=list, verbose_name='respuestas de diagnóstico')),
                ('adapted_content', models.TextField(blank=True, default='', verbose_name='contenido adaptado (markdown)')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_units', to='curriculum.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'unidad personalizada',
                'verbose_name_plural': 'unidades personalizadas',
                'indexes': [models.Index(fields=['user', 'unit'], name='learning_pe_user_id_246784_idx')],
                'unique_together': {('user', 'unit')},
            },
        ),
    ]
