# Generated by Django 5.1.15 on 2026-07-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_personalizedunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedunit',
            name='skipped',
            field=models.BooleanField(default=False, verbose_name='diagnóstico saltado'),
        ),
    ]
