# Generated by Django 5.1.15 on 2026-08-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_personalizedunit_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='reason',
            field=models.CharField(choices=[('incorrect', 'Incorrecta'), ('biased', 'Sesgada'), ('offtopic', 'Fuera de tema'), ('harmful', 'Dañina'), ('bug', 'Falla técnica'), ('other', 'Otra')], max_length=16, verbose_name='razón'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='source',
            field=models.CharField(choices=[('chat', 'Chat'), ('activity', 'Actividad'), ('content', 'Contenido'), ('platform', 'Plataforma / general')], max_length=16, verbose_name='origen'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='ID origen'),
        ),
    ]
