# Generated by Django 5.1.15 on 2026-08-07 22:54

import django.db.models.deletion
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_errorreport_reason_alter_errorreport_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDiagnosticResult',
            fields=[
                ('id', models.CharField(default=learning.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=list, verbose_name='respuestas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha/hora')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_diagnostic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resultado de diagnóstico del curso',
                'verbose_name_plural': 'resultados de diagnóstico del curso',
            },
        ),
        migrations.CreateModel(
            name='FinalExamAttempt',
            fields=[
                ('id', models.CharField(default=learning.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=list, verbose_name='respuestas (índices elegidos)')),
                ('score', models.IntegerField(verbose_name='puntaje (0-100)')),
                ('passed', models.BooleanField(verbose_name='¿aprobada?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha/hora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'intento de prueba de cierre',
                'verbose_name_plural': 'intentos de prueba de cierre',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='learning_fi_user_id_923dce_idx')],
            },
        ),
    ]
