# Generated by Django 5.1.15 on 2026-08-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_coursediagnosticresult_finalexamattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='source',
            field=models.CharField(choices=[('activity', 'Actividad'), ('content', 'Contenido'), ('platform', 'Plataforma / general')], max_length=16, verbose_name='origen'),
        ),
        migrations.DeleteModel(
            name='SelfAssessment',
        ),
    ]
