# Generated by Django 5.1.15 on 2026-10-05 23:53

import django.db.models.deletion
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_errorreport_source_delete_selfassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentConsent',
            fields=[
                ('id', models.CharField(default=learning.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('authorized', 'Autoriza el uso científico de sus datos'), ('rejected', 'No autoriza el uso científico de sus datos')], max_length=10, verbose_name='decisión')),
                ('version', models.CharField(max_length=20, verbose_name='versión del consentimiento')),
                ('research_code', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='código de investigación')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha/hora de la decisión')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha/hora del retiro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consentimiento informado',
                'verbose_name_plural': 'consentimientos informados',
            },
        ),
    ]
