# Generated by Django 5.1.15 on 2026-07-16 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('path', models.CharField(max_length=255, verbose_name='ruta')),
                ('method', models.CharField(max_length=8, verbose_name='método HTTP')),
                ('status_code', models.IntegerField(default=200, verbose_name='código de estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha/hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de acceso',
                'verbose_name_plural': 'registros de acceso',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='telemetry_a_user_id_67ff46_idx'), models.Index(fields=['-created_at'], name='telemetry_a_created_102548_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Vista de página'), ('open_lesson', 'Abrir lección'), ('open_activity', 'Abrir actividad'), ('request_hint', 'Solicitar pista'), ('submit_attempt', 'Enviar intento'), ('open_chat', 'Abrir tutor IA'), ('send_chat', 'Enviar mensaje al tutor'), ('rate_message', 'Calificar mensaje'), ('bookmark', 'Marcar actividad'), ('self_assess', 'Autoevaluación'), ('report_error', 'Reportar error de IA'), ('custom', 'Personalizado')], db_index=True, max_length=32, verbose_name='tipo de evento')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha/hora')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.activity')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.unit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='telemetry_e_user_id_c7bdaa_idx'), models.Index(fields=['event_type', '-created_at'], name='telemetry_e_event_t_25248c_idx')],
            },
        ),
    ]
