# Generated by Django 5.1.15 on 2026-08-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Vista de página'), ('open_lesson', 'Abrir lección'), ('open_activity', 'Abrir actividad'), ('request_hint', 'Solicitar pista'), ('submit_attempt', 'Enviar intento'), ('bookmark', 'Marcar actividad'), ('self_assess', 'Autoevaluación'), ('report_error', 'Reportar error'), ('custom', 'Personalizado')], db_index=True, max_length=32, verbose_name='tipo de evento'),
        ),
    ]
