# Generated by Django 5.1.15 on 2026-09-01 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_alter_eventlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Inicio de sesión exitoso'), ('login_failed', 'Inicio de sesión fallido'), ('password_change', 'Cambio de contraseña'), ('password_reset_admin', 'Reset de contraseña por docente'), ('student_created', 'Creación de cuenta de estudiante'), ('report_moderated', 'Moderación de reporte'), ('course_config_changed', 'Cambio de configuración del curso')], db_index=True, max_length=32, verbose_name='tipo de evento')),
                ('target', models.CharField(blank=True, default='', max_length=255, verbose_name='objetivo')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha/hora')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de auditoría',
                'verbose_name_plural': 'eventos de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='telemetry_a_actor_i_568f06_idx'), models.Index(fields=['event_type', '-created_at'], name='telemetry_a_event_t_981e02_idx')],
            },
        ),
    ]
