# Generated by Django 5.1.15 on 2026-10-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Inicio de sesión exitoso'), ('login_failed', 'Inicio de sesión fallido'), ('password_change', 'Cambio de contraseña'), ('password_reset_admin', 'Reset de contraseña por docente'), ('student_created', 'Creación de cuenta de estudiante'), ('report_moderated', 'Moderación de reporte'), ('course_config_changed', 'Cambio de configuración del curso'), ('consent_registered', 'Consentimiento informado registrado'), ('consent_revoked', 'Consentimiento informado revocado')], db_index=True, max_length=32, verbose_name='tipo de evento'),
        ),
    ]
