# Generated by Django 5.1.15 on 2026-07-16 06:09

import curriculum.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=curriculum.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=160)),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('content', models.TextField(blank=True, default='', verbose_name='contenido (markdown)')),
                ('duration_min', models.IntegerField(default=15, verbose_name='duración (min)')),
                ('order', models.IntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'lección',
                'verbose_name_plural': 'lecciones',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=curriculum.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='resumen')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('icon', models.CharField(default='BookOpen', max_length=64, verbose_name='icono')),
                ('color', models.CharField(default='sky', max_length=32, verbose_name='color')),
                ('order', models.IntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'unidad',
                'verbose_name_plural': 'unidades',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=curriculum.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('criteria', models.JSONField(default=list, verbose_name='criterios')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rúbrica',
                'verbose_name_plural': 'rúbricas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=curriculum.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('multiple_choice', 'Selección múltiple'), ('guided_problem', 'Problema guiado'), ('case_analysis', 'Análisis de caso'), ('progressive_exercise', 'Ejercicio progresivo'), ('self_assessment', 'Autoevaluación')], max_length=32, verbose_name='tipo')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('prompt', models.TextField(verbose_name='enunciado')),
                ('data', models.JSONField(default=dict, verbose_name='datos (opciones, respuesta, pistas...)')),
                ('points', models.IntegerField(default=10, verbose_name='puntos')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Media'), ('hard', 'Difícil')], default='medium', max_length=16, verbose_name='dificultad')),
                ('order', models.IntegerField(default=0, verbose_name='orden')),
                ('assessment_type', models.CharField(choices=[('diagnostic', 'Diagnóstica'), ('formative', 'Formativa'), ('summative', 'Sumativa'), ('self_reflection', 'Auto-reflexión')], default='formative', max_length=24, verbose_name='tipo de evaluación')),
                ('bloom_level', models.CharField(choices=[('remember', 'Recordar'), ('understand', 'Comprender'), ('apply', 'Aplicar'), ('analyze', 'Analizar'), ('evaluate', 'Evaluar'), ('create', 'Crear')], default='apply', max_length=16, verbose_name='nivel Bloom')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='intentos máximos (0=ilimitado)')),
                ('mastery_threshold', models.IntegerField(default=70, verbose_name='umbral de dominio (%)')),
                ('weight', models.IntegerField(default=1, verbose_name='peso en la unidad')),
                ('time_limit_min', models.IntegerField(blank=True, null=True, verbose_name='límite de tiempo (min)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='curriculum.lesson')),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='curriculum.rubric')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.unit'),
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=curriculum.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, verbose_name='código')),
                ('description', models.TextField(verbose_name='descripción')),
                ('bloom_level', models.CharField(default='apply', max_length=16, verbose_name='nivel Bloom')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='curriculum.lesson')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='curriculum.unit')),
            ],
            options={
                'verbose_name': 'objetivo de aprendizaje',
                'verbose_name_plural': 'objetivos de aprendizaje',
            },
        ),
        migrations.CreateModel(
            name='ActivityObjective',
            fields=[
                ('id', models.CharField(default=curriculum.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='curriculum.activity')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='curriculum.learningobjective')),
            ],
            options={
                'verbose_name': 'actividad-objetivo',
                'verbose_name_plural': 'actividades-objetivos',
                'indexes': [models.Index(fields=['activity'], name='curriculum__activit_f70bd8_idx')],
                'unique_together': {('activity', 'objective')},
            },
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['author'], name='curriculum__author__995d62_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['lesson'], name='curriculum__lesson__db5e26_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['assessment_type'], name='curriculum__assessm_f433f8_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['unit'], name='curriculum__unit_id_5055c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('unit', 'slug')},
        ),
        migrations.AddIndex(
            model_name='learningobjective',
            index=models.Index(fields=['unit'], name='curriculum__unit_id_81caa9_idx'),
        ),
        migrations.AddIndex(
            model_name='learningobjective',
            index=models.Index(fields=['lesson'], name='curriculum__lesson__93e5ae_idx'),
        ),
    ]
