# Generated by Django 5.1.15 on 2026-07-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='contenido base (markdown)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='diagnostic_questions',
            field=models.JSONField(default=list, verbose_name='preguntas de diagnóstico'),
        ),
    ]
