# Generated by Django 5.1.15 on 2026-07-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_unit_content_unit_diagnostic_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='publicada'),
        ),
    ]
