# Generated by Django 5.1.15 on 2026-08-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_lesson_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic_questions', models.JSONField(default=list, verbose_name='preguntas del diagnóstico general')),
                ('final_exam_questions', models.JSONField(default=list, verbose_name='preguntas de la prueba de cierre')),
                ('final_exam_pass_score', models.IntegerField(default=70, verbose_name='puntaje mínimo de aprobación (%)')),
                ('final_exam_max_attempts', models.IntegerField(default=3, verbose_name='intentos máximos de la prueba de cierre')),
            ],
            options={
                'verbose_name': 'configuración del curso',
                'verbose_name_plural': 'configuración del curso',
            },
        ),
        migrations.RemoveField(
            model_name='unit',
            name='diagnostic_questions',
        ),
    ]
