# Generated by Django 5.1.15 on 2026-07-16 06:09

import django.db.models.deletion
import sandbox.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=sandbox.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('color', models.CharField(default='sky', max_length=32, verbose_name='color')),
                ('icon', models.CharField(default='BookOpen', max_length=64, verbose_name='icono')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=16, verbose_name='estado')),
                ('order', models.IntegerField(default=0, verbose_name='orden')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'curso (sandbox)',
                'verbose_name_plural': 'cursos (sandbox)',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=sandbox.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='resumen')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('icon', models.CharField(default='BookOpen', max_length=64, verbose_name='icono')),
                ('color', models.CharField(default='sky', max_length=32, verbose_name='color')),
                ('order', models.IntegerField(default=0, verbose_name='orden')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='sandbox.course')),
            ],
            options={
                'verbose_name': 'unidad (sandbox)',
                'verbose_name_plural': 'unidades (sandbox)',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=sandbox.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('content', models.TextField(blank=True, default='', verbose_name='contenido (markdown)')),
                ('duration_min', models.IntegerField(default=15, verbose_name='duración (min)')),
                ('order', models.IntegerField(default=0, verbose_name='orden')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='sandbox.courseunit')),
            ],
            options={
                'verbose_name': 'lección (sandbox)',
                'verbose_name_plural': 'lecciones (sandbox)',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DataResource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=sandbox.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('type', models.CharField(max_length=32, verbose_name='tipo')),
                ('content', models.TextField(verbose_name='contenido')),
                ('tags', models.CharField(blank=True, default='', max_length=255, verbose_name='etiquetas')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recurso de datos',
                'verbose_name_plural': 'recursos de datos',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=sandbox.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('category', models.CharField(default='general', max_length=32, verbose_name='categoría')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'banco de preguntas',
                'verbose_name_plural': 'bancos de preguntas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=sandbox.models._cuid_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32, verbose_name='tipo')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('prompt', models.TextField(verbose_name='enunciado')),
                ('data', models.JSONField(default=dict, verbose_name='datos')),
                ('points', models.IntegerField(default=10, verbose_name='puntos')),
                ('difficulty', models.CharField(default='medium', max_length=16, verbose_name='dificultad')),
                ('tags', models.CharField(blank=True, default='', max_length=255, verbose_name='etiquetas')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sandbox.courselesson')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='sandbox.questionbank')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['author'], name='sandbox_cou_author__cd6d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='sandbox_cou_status_da5afe_idx'),
        ),
        migrations.AddIndex(
            model_name='courseunit',
            index=models.Index(fields=['course'], name='sandbox_cou_course__b71314_idx'),
        ),
        migrations.AddIndex(
            model_name='courselesson',
            index=models.Index(fields=['unit'], name='sandbox_cou_unit_id_e0fde0_idx'),
        ),
        migrations.AddIndex(
            model_name='dataresource',
            index=models.Index(fields=['author'], name='sandbox_dat_author__575407_idx'),
        ),
        migrations.AddIndex(
            model_name='dataresource',
            index=models.Index(fields=['type'], name='sandbox_dat_type_e4ec27_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['author'], name='sandbox_que_author__159804_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['category'], name='sandbox_que_categor_bd5fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['bank'], name='sandbox_que_bank_id_265878_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['lesson'], name='sandbox_que_lesson__bd18d7_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type'], name='sandbox_que_type_a930cc_idx'),
        ),
    ]
